Fail_alert testing

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -35,19 +35,204 @@ commands:
           temoji=%E2%9C%85
           curl << parameters.webhook >>/sendMessage?"chat_id=<< parameters.groupid >>&text=%F0%9F%94%89 Below are the details of your build: %0A %F0%9F%95%9C Date: $(date) %0A $temoji BUILD_URL: ${CIRCLE_BUILD_URL} %0A $temoji BUILD_NUMBER: ${CIRCLE_BUILD_NUM} %0A $temoji TRIGGERER: ${CIRCLE_USERNAME} %0A %F0%9F%93%8B MESSAGE: << parameters.message >> %0A"
           fi
-  failalert:
-    description: >
-       A handy command to notify a Slack channel on failure in the default master branch
+  status:
+    description: |
+      Send a status alert at the end of a job based on success or failure. Must be the last step in a job.
     parameters:
+      channel:
+        default: ${TELEGRAM_GROUPID}
+        description: |
+          ID of channel if set, overrides webhook's default channel setting
+        type: string
+      fail_only:
+        default: false
+        description: |
+          If `true`, notifications successful jobs will not be sent
+        type: boolean
+      failure_message:
+        default: ':red_circle: A $CIRCLE_JOB job has failed!'
+        description: Enter custom message.
+        type: string
+      include_job_number_field:
+        default: true
+        description: |
+          Whether or not to include the Job Number field in the message
+        type: boolean
+      include_project_field:
+        default: true
+        description: |
+          Whether or not to include the Project field in the message
+        type: boolean
+      include_visit_job_action:
+        default: true
+        description: |
+          Whether or not to include the Visit Job action in the message
+        type: boolean
+      mentions:
+        default: ""
+        description: |
+          A comma separated list of user IDs. No spaces.
+        type: string
       only_for_branches:
-        default: ''
-        description: >
-          If set, a comma-separated list of branches for which to sendnotifications. No spaces.
+        default: ""
+        description: |
+          If set, a comma-separated list of branches for which to send notifications. No spaces.
+        type: string
+      success_message:
+        default: ':tada: A $CIRCLE_JOB job has succeeded!'
+        description: Enter custom message.
+        type: string
+      webhook:
+        default: ${TELEGRAM_WEBHOOK}
+        description: |
+          Enter either your Webhook value or use the CircleCI UI to add your token under the 'TELEGRAM_WEBHOOK' env var
         type: string
     steps:
-    - status:
-        fail_only: true
-        only_for_branches: <<parameters.only_for_branches>>
+    - run:
+        command: |
+          echo 'export TELEGRAM_BUILD_STATUS="fail"' >> $BASH_ENV
+        name: TELEGRAM - Setting Failure Condition
+        when: on_fail
+    - run:
+        command: |
+          echo 'export TELEGRAM_BUILD_STATUS="success"' >> $BASH_ENV
+        name: TELEGRAM - Setting Success Condition
+        when: on_success
+    - run:
+        command: |
+          if [ ! -x /bin/bash ]; then
+            echo Bash not installed.
+            exit 1
+          fi
+        name: Provide error if non-bash shell
+    - run:
+        command: |
+          current_branch_in_filter=false
+
+          IFS="," read -ra BRANCH_FILTERS \<<< "<< parameters.only_for_branches >>"
+
+          for i in "${BRANCH_FILTERS[@]}"; do
+            if [ "${i}" == "${CIRCLE_BRANCH}" ]; then
+              current_branch_in_filter=true
+            fi
+          done
+
+          if [ "x" == "x<< parameters.only_for_branches>>" ] || [ "$current_branch_in_filter" = true ]; then
+            # Provide error if no webhook is set and error. Otherwise continue
+            if [ -z "<< parameters.webhook >>" ]; then
+              echo "NO TELEGRAM WEBHOOK SET"
+              echo "Please input your TELEGRAM_WEBHOOK value either in the settings for this project, or as a parameter for this orb."
+              exit 1
+            else
+              #Create Members string
+              if [ -n "<< parameters.mentions >>" ]; then
+                IFS="," read -ra TELEGRAM_MEMBERS \<<< "<< parameters.mentions >>"
+                for i in "${TELEGRAM_MEMBERS[@]}"; do
+                  if [ $(echo ${i} | head -c 1) == "S" ]; then
+                    TELEGRAM_MENTIONS="${TELEGRAM_MENTIONS}<!subteam^${i}> "
+                  elif echo ${i} | grep -E "^(here|channel|everyone)$" > /dev/null; then
+                    TELEGRAM_MENTIONS="${TELEGRAM_MENTIONS}<!${i}> "
+                  else
+                    TELEGRAM_MENTIONS="${TELEGRAM_MENTIONS}<@${i}> "
+                  fi
+                done
+              fi
+              #If successful
+              if [ "$TELEGRAM_BUILD_STATUS" = "success" ]; then
+                #Skip if fail_only
+                if [ << parameters.fail_only >> = true ]; then
+                  echo "The job completed successfully"
+                  echo '"fail_only" is set to "true". No TELEGRAM notification sent.'
+                else
+                  curl -X POST -H 'Content-type: application/json' \
+                    --data "{ \
+                              <<# parameters.channel >>
+                              \"channel\": \"<< parameters.channel >>\", \
+                              <</ parameters.channel >>
+                              \"attachments\": [ \
+                                { \
+                                  \"fallback\": \"<< parameters.success_message >>\", \
+                                  \"text\": \"<< parameters.success_message >> $TELEGRAM_MENTIONS\", \
+                                  \"fields\": [ \
+                                    <<# parameters.include_project_field >>
+                                    { \
+                                      \"title\": \"Project\", \
+                                      \"value\": \"$CIRCLE_PROJECT_REPONAME\", \
+                                      \"short\": true \
+                                    }, \
+                                    <</ parameters.include_project_field >>
+                                    <<# parameters.include_job_number_field >>
+                                    { \
+                                      \"title\": \"Job Number\", \
+                                      \"value\": \"$CIRCLE_BUILD_NUM\", \
+                                      \"short\": true \
+                                    } \
+                                    <</ parameters.include_job_number_field >>
+                                  ], \
+                                  \"actions\": [ \
+                                    <<# parameters.include_visit_job_action >>
+                                    { \
+                                      \"type\": \"button\", \
+                                      \"text\": \"Visit Job\", \
+                                      \"url\": \"$CIRCLE_BUILD_URL\" \
+                                    } \
+                                    <</ parameters.include_visit_job_action >>
+                                  ], \
+                                  \"color\": \"#1CBF43\" \
+                                } \
+                              ] \
+                            } " << parameters.webhook >>
+                  echo "Job completed successfully. Alert sent."
+                fi
+              else
+                #If Failed
+                curl -X POST -H 'Content-type: application/json' \
+                  --data "{ \
+                    <<# parameters.channel >>
+                    \"channel\": \"<< parameters.channel >>\", \
+                    <</ parameters.channel >>
+                    \"attachments\": [ \
+                      { \
+                        \"fallback\": \"<< parameters.failure_message >>\", \
+                        \"text\": \"<< parameters.failure_message >> $TELEGRAM_MENTIONS\", \
+                        \"fields\": [ \
+                          <<# parameters.include_project_field >>
+                          { \
+                            \"title\": \"Project\", \
+                            \"value\": \"$CIRCLE_PROJECT_REPONAME\", \
+                            \"short\": true \
+                          }, \
+                          <</ parameters.include_project_field >>
+                          <<# parameters.include_job_number_field >>
+                          { \
+                            \"title\": \"Job Number\", \
+                            \"value\": \"$CIRCLE_BUILD_NUM\", \
+                            \"short\": true \
+                          } \
+                          <</ parameters.include_job_number_field >>
+                        ], \
+                        \"actions\": [ \
+                          <<# parameters.include_visit_job_action >>
+                          { \
+                            \"type\": \"button\", \
+                            \"text\": \"Visit Job\", \
+                            \"url\": \"$CIRCLE_BUILD_URL\" \
+                          } \
+                          <</ parameters.include_visit_job_action >>
+                        ], \
+                        \"color\": \"#ed5c5c\" \
+                      } \
+                    ] \
+                  } " << parameters.webhook >>
+                echo "Job failed. Alert sent."
+              fi
+            fi
+          else
+            echo "Current branch is not included in only_for_branches filter; no status alert will be sent"
+          fi
+        name: TELEGRAM - Sending Status Alert
+        shell: /bin/bash
+        when: always
 
 executors:
   default:
@@ -59,4 +244,9 @@ jobs:
     executor: default
     steps:
       - checkout # check out the code in the project directory
-      - failalert # Fail alert Notification
+      - run: exit 0
+      
+      - status:
+         fail_only: true
+         only_for_branches: "master"
+
