Testing Fail Alert

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,13 +2,13 @@
 # Telegram bot cannot send direct messages to the users for security and privacy reasons.
 # Use BotFather bot of telegram to create a telegram bot and get API key.
 # Author: Pawan Bahuguna
-# Verision: 1.0
+# Verision: 1.0.1
 
 version: 2.1
 
 commands:
   notification:
-    description: Send notification to Telegram group.
+    description: Send notification to Telegram group when jobs are successful.
     parameters:
       webhook:
         default: ${TELEGRAM_WEBHOOK}
@@ -33,9 +33,39 @@ commands:
             echo "Please input your TELEGRAM_WEBHOOK value either in the settings for this project, or as a parameter for this orb." && exit 1
           else
           temoji=%E2%9C%85
-          curl -X POST -H 'Content-type: application/json' << parameters.webhook >>/sendMessage?"chat_id=<< parameters.groupid >>&text=%F0%9F%94%89 Below are the details of your build: %0A %F0%9F%95%9C Date: $(date) %0A $temoji BUILD_URL: ${CIRCLE_BUILD_URL} %0A $temoji BUILD_NUMBER: ${CIRCLE_BUILD_NUM} %0A $temoji TRIGGERER: ${CIRCLE_USERNAME} %0A %F0%9F%93%8B MESSAGE: << parameters.message >> %0A"
+          curl << parameters.webhook >>/sendMessage?"chat_id=<< parameters.groupid >>&text=%F0%9F%94%89 Below are the details of your build: %0A %F0%9F%95%9C Date: $(date) %0A $temoji BUILD_URL: ${CIRCLE_BUILD_URL} %0A $temoji BUILD_NUMBER: ${CIRCLE_BUILD_NUM} %0A $temoji TRIGGERER: ${CIRCLE_USERNAME} %0A %F0%9F%93%8B MESSAGE: << parameters.message >> %0A"
           fi
-         
+  failalert:
+    description: Send fail alert to Telegram group when jobs fail.
+    parameters:
+      webhook:
+        default: ${TELEGRAM_WEBHOOK}
+        description: Enter either your Webhook value or use the CircleCI UI to add
+          your token under the 'TELEGRAM_WEBHOOK' env var
+        type: string
+      groupid:
+        default: ${TELEGRAM_GROUPID}
+        description: Enter Telegram Group ID or use the CircleCI UI to add
+          it under the 'TELEGRAM_GROUPID' env var. Not recommended to mention view orb.
+        type: integer
+      fail_message:
+        default: "$CIRCLE_JOB Job Faild, please check Job BUILD URL"
+        description: Enter your custom message. This is optional.
+        type: string
+    steps:
+    - status:
+      fail_only: true
+    - run:
+       name: Sending fail alert to Telegram group.
+       command: |
+          if [ -z "<< parameters.webhook >>" ]; then
+            echo "NO Telegram WEBHOOK SET"
+            echo "Please input your TELEGRAM_WEBHOOK value either in the settings for this project, or as a parameter for this orb." && exit 1
+          else
+          temoji=%E2%9D%8C
+          curl << parameters.webhook >>/sendMessage?"chat_id=<< parameters.groupid >>&text=%F0%9F%86%98 Below are details of Failed Build: %0A %F0%9F%95%9C Date: $(date) %0A $temoji BUILD_URL: ${CIRCLE_BUILD_URL} %0A $temoji BUILD_NUMBER: ${CIRCLE_BUILD_NUM} %0A $temoji TRIGGERER: ${CIRCLE_USERNAME} %0A %F0%9F%93%8B MESSAGE: << parameters.message >> %0A"
+          fi
+
 executors:
   default:
     docker:
@@ -46,6 +76,4 @@ jobs:
     executor: default
     steps:
       - checkout # check out the code in the project directory
-      - notification: # using Notification Command
-          groupid: "-396455440" # Not recommended as it will show in build logs. Use variable instead via CircleCI UI.
-          message: Good work team.
+      - failalert # Fail alert Notification
